const PRODUCTS = [
  { id:1, name:"Bouée Flamant Rose XL", category:"Bouées de Plage", price:34.90, original:49.90, badge:"sale", emoji:"🦩", img:"https://images.unsplash.com/photo-1559827291-72ee739d0d9a?w=600&q=80", stars:4.9, reviews:312, desc:"Bouée géante flamant rose en vinyle épais résistant aux UV. Livrée avec pompe à main incluse.", details:"Dimensions gonflées : 180×120 cm. Vinyle PVC renforcé 0,35 mm résistant aux UV et au chlore. Valve double action. Poids à vide : 900 g. Capacité max : 90 kg. Mini-pompe à main incluse. Coloris : Rose Nacré.", filter:["promo","populaire"] },
  { id:2, name:"Bouée Licorne Arc-en-Ciel", category:"Bouées de Plage", price:29.90, original:null, badge:"new", emoji:"🦄", img:"https://images.unsplash.com/photo-1563911302283-d2bc129e7570?w=600&q=80", stars:4.8, reviews:187, desc:"Bouée licorne pastel aux couleurs arc-en-ciel. Dès 8 ans. Parfaite piscine et plage.", details:"Dimensions : 160×100 cm. PVC haute résistance, résistant au chlore et aux UV. Couleurs pastel arc-en-ciel. Valve triple action. Certification sécurité CE. Poids à vide : 750 g. Livraison sous 48h.", filter:"nouveautes" },
  { id:3, name:"Transat Teck & Cordage Marin", category:"Transats", price:189.00, original:null, badge:"popular", emoji:"🪑", img:"https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=600&q=80", stars:5.0, reviews:98, desc:"Transat en teck FSC et cordage coton nautique. 5 positions de dossier. L'élégance bord de mer.", details:"Structure teck massif certifié FSC. Cordage coton nautique résistant eau salée et chlore. 5 positions de dossier. Dimensions : 190×60 cm. Poids : 8 kg. Livré assemblé avec coussin amovible.", filter:"populaire" },
  { id:4, name:"Transat Gonflable Lounge", category:"Transats", price:79.00, original:99.00, badge:"sale", emoji:"🛋️", img:"https://images.unsplash.com/photo-1530549387789-4c1017266635?w=600&q=80", stars:4.7, reviews:143, desc:"Transat gonflable 2-en-1 : flottant en piscine ou confort sur plage. Ultra-rapide à gonfler.", details:"Gonflage en 30 secondes. Flotteur intégré. Repose-tête intégré. Capacité 120 kg. Dimensions gonflées : 175×70 cm. Polyester Oxford imperméable. Coloris : Bleu Lagon / Corail.", filter:["promo"] },
  { id:5, name:"Matelas Île Flottante XL", category:"Matelas Gonflables", price:89.00, original:119.00, badge:"sale", emoji:"🏝️", img:"https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600&q=80", stars:4.9, reviews:256, desc:"Matelas île flottante XXL pour 2 personnes. Porte-gobelets et poignées intégrés.", details:"Dimensions : 220×180 cm. Capacité : 2 pers. (200 kg). PVC triple couche anti-crevaison. 4 poignées de stabilisation. 2 porte-gobelets. Compatible pompe électrique. Coloris : Turquoise Lagon.", filter:["promo","populaire"] },
  { id:6, name:"Matelas Flottant Double Arc-en-Ciel", category:"Matelas Gonflables", price:65.00, original:null, badge:"new", emoji:"🌈", img:"https://images.unsplash.com/photo-1534359265607-b5927d906cc8?w=600&q=80", stars:4.8, reviews:89, desc:"Matelas flottant arc-en-ciel pour 2. Surface velours douce. Déflation ultra-rapide.", details:"Surface velours polyester doux. Dimensions : 200×160 cm. Fond PVC antidérapant. Valve à déflation rapide. Convient piscine et eau calme. Nettoyage à l'eau claire. Coloris : Arc-en-ciel pastel.", filter:"nouveautes" },
  { id:7, name:"Seaglide Pro 300", category:"Seaglides", price:349.00, original:null, badge:"new", emoji:"🤿", img:"https://images.unsplash.com/photo-1682687982501-1e58ab814714?w=600&q=80", stars:4.9, reviews:47, desc:"Scooter sous-marin professionnel. 3 km/h, autonomie 45 min. Étanche jusqu'à 40 m.", details:"Moteur brushless 150W. Vitesse max : 3 km/h. Autonomie : 45 min. Profondeur max : 40 m. Batterie lithium rechargeable (recharge 2h). Poids : 2,8 kg. Livré avec sac transport étanche.", filter:"nouveautes" },
  { id:8, name:"Seaglide Explorer Junior", category:"Seaglides", price:199.00, original:249.00, badge:"sale", emoji:"🌊", img:"https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=600&q=80", stars:4.7, reviews:63, desc:"Seaglide enfant dès 10 ans. 2 km/h, 30 min d'autonomie. Sécurité certifiée CE.", details:"Pour enfants dès 10 ans. Vitesse : 2 km/h. Autonomie : 30 min. Profondeur max : 15 m. Poignée ergonomique antidérapante. Arrêt automatique de sécurité. Batterie rechargeable. Poids : 1,9 kg.", filter:["promo"] },
  { id:9, name:"Paddle Gonflable Bass Hunter 11'6\"", category:"Paddles", price:449.00, original:549.00, badge:"new", emoji:"🏄", img:"paddle-1.jpg", images:["paddle-1.jpg","paddle-2.jpg","paddle-3.jpg"], stars:4.9, reviews:128, desc:"Stand Up Paddle gonflable ultra-stable 11'6\". Supporte jusqu'à 195 kg. Idéal rivière, lac et mer.", details:"Dimensions : 350×86×15 cm (11'6\"×34\"×6\"). Poids max : 195 kg (430 lb). Pression : 12–15 PSI. Construction Drop-Stitch haute densité. Livré avec pagaie, pompe, leash et sac de transport. Conçu pour la pêche et la balade.", filter:["nouveautes","populaire"] },
  { id:10, name:"Seaglide Spinera Catua", category:"Seaglides", price:1290.00, original:1490.00, badge:"new", emoji:"🤿", img:"seaglide-1.jpg", images:["seaglide-1.jpg","seaglide-2.jpg","seaglide-3.jpg"], stars:4.9, reviews:34, desc:"Scooter sous-marin connecté Spinera. 3 vitesses, écran LED, se fixe aussi sur paddle et kayak.", details:"Moteur puissant 3 vitesses (Low / Normal / High). Écran LED indiquant batterie et mode. Fixation universelle pour paddle et kayak (montage rapide). Bandoulières de transport incluses. Étanche, conçu pour l'eau douce et salée. Batterie rechargeable haute autonomie. Coloris : Noir / Cyan.", filter:["nouveautes","populaire"] },
  { id:11, name:"Chaise Flottante Tropicale", category:"Matelas Gonflables", price:39.90, original:54.90, badge:"sale", emoji:"🪑", img:"chaise-1.jpg", images:["chaise-1.jpg","chaise-2.jpg","chaise-3.jpg"], stars:4.8, reviews:156, desc:"Chaise longue gonflable flottante avec dossier. Motif tropical bleu. Confort et stabilité dans l'eau.", details:"Dimensions : 76×41×61 cm (30\"×16\"×24\"). Dossier confortable et assise immergée. Tissu motif feuilles tropicales résistant aux UV. Gonflage rapide. Sangles de maintien. Idéale piscine et eau calme. Capacité max : 100 kg. Coloris : Bleu Tropical.", filter:["promo","populaire"] },
  { id:12, name:"AirFlow Mini Ventilateur Portable", category:"Accessoires Soleil", price:29.90, original:39.90, badge:"new", emoji:"💨", img:"airflow-1.jpg", images:["airflow-1.jpg","airflow-2.jpg","airflow-3.jpg"], stars:4.9, reviews:203, desc:"Mini ventilateur portable AirFlow. Design premium, ventilateur dorée silencieux. Idéal plage, piscine et terrasse. 3 coloris.", details:"Ventilateur à turbine dorée silencieux. 3 vitesses. Batterie rechargeable USB-C (autonomie 8h). Design arrondi ergonomique avec boucle de suspension. Ultra-compact : tient dans la paume. 3 coloris : Rose Blush, Blanc Ivoire, Vert Sauge. Idéal plage, terrasse, voyage.", filter:["nouveautes","populaire"] }
];
